<?php
session_start();
include_once("config.php");
include_once("support.php");

?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Reconstructer - <?php echo $APP_TITLE_SHORT; ?></title>
	<link rel="stylesheet" href="css/styles.css">
	<link rel="shortcut icon" href="http://www.latrobe.edu.au/favicon.ico" />
</head>
<body>
	<h1><?php echo $APP_TITLE_LONG; ?></h1>
	<hr class="rule"/>
	<div class="links"><ul><li><a href="./">Home</a></li><li> &gt; Reconstructer</li></ul></div>
	<hr class="rule"/>
	<div class="headertext"><strong>Description</strong>: This tool replaces barcodes with the original amino acids. This process restores the true sequences once they been re-aligned by any standard alignment program.</div>
	<div class="headertext"><strong>Instructions</strong>: Enter the Job Number generated by the barcoder tool (to restore the correct amino acids in place of the barcodes).</div>
	
<?php
    if (isset($_SESSION['msg'])) {
?>
    <div class="errormsg"><?php print $_SESSION['msg']; ?></div>
<?php
    }
    unset($_SESSION['msg']);
?>

	<form method="GET" action="reconstructer.php">
    <div class="jobid">
	    <table class="results">
		<tbody>
		    <tr>
		        <th class="headingcol heading">Job Number:</th>
		        <td><input type="text" name="j" value="" /></td>
		    </tr>
		</tbody>
		</table>
    </div>

	<div class="control">
		<input type="submit" class="defaultsubmit" value="Load job details"/>
	</div>
	</form>

	<hr class="rule"/>
	<div class="footerimgs">
		<div class="leftimg"><a href="http://www.hexima.com.au/"><img src="img/hexima.png" height="80px" alt="Hexima Logo" /></a></div>
		<div class="rightimg"><a href="http://www.latrobe.edu.au/lims/"><img src="img/lims.png" height="80px" alt="LIMS Logo" /></a></div>
	</div>
	<p class="footer">Developed by Thomas Shafee</p>
</body>
</html>

