<?php
session_start();
include_once("config.php");
include_once("support.php");

$jobid = "";
if (isset($_GET['j']))
	$jobid=san_jobid($_GET['j']);
$seq= popKey($_SESSION, 'seq', "");

if ($jobid == "") {
    header("location: reconstructer_jobid.php");
    exit();
}

if (!is_dir("$RESULT_DIR/$jobid") || !is_file("$RESULT_DIR/$jobid/$PARAM_FILE"))
{
    $_SESSION['msg'] = "Failed to find your job details.  Please try again and if that fails contact the system admin.";

    header("location: reconstructer_jobid.php");
    exit();
}

// load job details from file
$params = array_map("trim", file("$RESULT_DIR/$jobid/$PARAM_FILE"));
$c = array_slice($params, 0, 8);
$bc = array_slice($params, 8, 8);

if (count($c) != 8 || count($bc) != 8)
{
    $_SESSION['msg'] = "Failed to find your job details.  Please try again and if that fails contact the system admin.";

    header("location: reconstructer_jobid.php");
    exit();
}

?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Reconstructer - <?php echo $APP_TITLE_SHORT; ?></title>
	<link rel="stylesheet" href="css/styles.css">
	<link rel="shortcut icon" href="http://www.latrobe.edu.au/favicon.ico" />
</head>
<body>
	<h1><?php echo $APP_TITLE_LONG; ?></h1>
	<hr class="rule"/>
	<div class="links"><ul><li><a href="./">Home</a></li><li> &gt; Reconstructer</li></ul></div>
	<hr class="rule"/>
	<div class="headertext"><strong>Description</strong>: This tool replaces barcodes with the original amino acids. This process restores the true sequences once they been re-aligned by any standard alignment program.</div>
	<div class="headertext"><strong>Instructions</strong>: Paste the barcoded sequence alignment (fasta format) into the box below. If non-default barcode sequences were used for the barcoder tool, specify them here. Enter the Job Number generated by the barcoder tool (to restore the correct amino acids in place of the barcodes).</div>

<?php
    if (isset($_SESSION['msg'])) {
?>
    <div class="errormsg"><?php print $_SESSION['msg']; ?></div>
<?php
    }
    unset($_SESSION['msg']);
?>

	<form method="POST" action="reconstructer_proc.php">
    <div class="jobid">
	    <table class="results">
		<tbody>
		    <tr>
		        <th class="headingcol heading">Job Number:</th>
		        <td><input type="text" name="j" value="<?php echo $jobid; ?>" /></td>
		    </tr>
		</tbody>
		</table>
    </div>
	<div class="params">
		<table>
		<thead>
			<tr>
				<th class="num">#</th>
				<th class="bc">Barcode</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td class="num">1</td>
				<td class="bc"><input type="text" name="bc1" readonly="readonly" value="<?php echo htmlspecialchars($bc[0]); ?>"/></td>
			</tr>
			<tr>
				<td class="num">2</td>
				<td class="bc"><input type="text" name="bc2" readonly="readonly" value="<?php echo htmlspecialchars($bc[1]); ?>"/></td>
			</tr>
			<tr>
				<td class="num">3</td>
				<td class="bc"><input type="text" name="bc3" readonly="readonly" value="<?php echo htmlspecialchars($bc[2]); ?>"/></td>
			</tr>
			<tr>
				<td class="num">4</td>
				<td class="bc"><input type="text" name="bc4" readonly="readonly" value="<?php echo htmlspecialchars($bc[3]); ?>"/></td>
			</tr>
			<tr>
				<td class="num">5</td>
				<td class="bc"><input type="text" name="bc5" readonly="readonly" value="<?php echo htmlspecialchars($bc[4]); ?>"/></td>
			</tr>
			<tr>
				<td class="num">6</td>
				<td class="bc"><input type="text" name="bc6" readonly="readonly" value="<?php echo htmlspecialchars($bc[5]); ?>"/></td>
			</tr>
			<tr>
				<td class="num">7</td>
				<td class="bc"><input type="text" name="bc7" readonly="readonly" value="<?php echo htmlspecialchars($bc[6]); ?>"/></td>
			</tr>
			<tr>
				<td class="num">8</td>
				<td class="bc"><input type="text" name="bc8" readonly="readonly" value="<?php echo htmlspecialchars($bc[7]); ?>"/></td>
			</tr>
		</tbody>
		</table>
	</div>
	<div class="seq">
		<label for="seq">FastA (previously barcoded) sequences</label>
		<textarea id="seq" name="seq" class="seq"><?php echo htmlspecialchars($seq); ?></textarea>
	</div>
	<div class="control">
		<div class="submittext">The job should take no longer than a few minutes</div>
		<input type="submit" class="defaultsubmit" value="Reconstruct Sequences"/>
	</div>
	</form>

	<hr class="rule"/>
	<div class="footerimgs">
		<div class="leftimg"><a href="http://www.hexima.com.au/"><img src="img/hexima.png" height="80px" alt="Hexima Logo" /></a></div>
		<div class="rightimg"><a href="http://www.latrobe.edu.au/lims/"><img src="img/lims.png" height="80px" alt="LIMS Logo" /></a></div>
	</div>
	<p class="footer">Developed by Thomas Shafee</p>
</body>
</html>

